version: '3'

services:
  chat-server-postgres:
    image: postgres:11.2
    command: ["-c", "max_connections=300"]
    volumes:
      - chat-svr-db-data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      TZ: Asia/Shanghai
    container_name: chat_server_postgres

  chat-server-redis:
    image: redis:5.0.5
    ports:
      - 6379:6379
    volumes:
      - chat-svr-redis-data:/data
    environment:
      TZ: Asia/Shanghai
    container_name: chat_server_redis
    
volumes:
  chat-svr-db-data:
    driver: local
  chat-svr-redis-data:
    driver: local

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.110.0.0/16
